######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 29 08:48:13 2010
######################################################################

DEPENDPATH += .  ../ccmain/
INCLUDEPATH += .

# Input
HEADERS += scrollview.h svmnode.h svutil.h
SOURCES += scrollview.cpp svmnode.cpp svutil.cpp
